In [9]:
import numpy as np

x = np.arange(2,33,2).reshape(4,4)

print(x)
    

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [14]:
x = np.arange(1, 26).reshape(5,5)
odd = x%2!= 0
y= x[odd] 
print(x)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [15]:
x = np.tile(np.arange(1, 5), (4, 1)).T
print(x)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
